# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_pagina.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 617)
        MainWindow.setMaximumSize(QtCore.QSize(730, 700))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_sair = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_sair.setFont(font)
        self.bt_sair.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_sair.setObjectName("bt_sair")
        self.verticalLayout.addWidget(self.bt_sair)
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pages.setObjectName("pages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 10, 721, 511))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.line_pesquisar = QtWidgets.QLineEdit(self.page_2)
        self.line_pesquisar.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.line_pesquisar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.line_pesquisar.setInputMask("")
        self.line_pesquisar.setMaxLength(11)
        self.line_pesquisar.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.line_pesquisar.setObjectName("line_pesquisar")
        self.bt_editar = QtWidgets.QPushButton(self.page_2)
        self.bt_editar.setGeometry(QtCore.QRect(10, 350, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_editar.setFont(font)
        self.bt_editar.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_editar.setObjectName("bt_editar")
        self.bt_deletar = QtWidgets.QPushButton(self.page_2)
        self.bt_deletar.setGeometry(QtCore.QRect(10, 440, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_deletar.setFont(font)
        self.bt_deletar.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_deletar.setObjectName("bt_deletar")
        self.bt_pdf = QtWidgets.QPushButton(self.page_2)
        self.bt_pdf.setGeometry(QtCore.QRect(10, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_pdf.setFont(font)
        self.bt_pdf.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_pdf.setObjectName("bt_pdf")
        self.bt_excel = QtWidgets.QPushButton(self.page_2)
        self.bt_excel.setGeometry(QtCore.QRect(10, 250, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_excel.setFont(font)
        self.bt_excel.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    \n"
"    \n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_excel.setObjectName("bt_excel")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(50, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(200, 40, 501, 441))
        self.tableWidget.setBaseSize(QtCore.QSize(500, 200))
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 170, 255);\n"
"border-radius:15px;\n"
"border-width:2px;\n"
"border-color:black;")
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pages.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(190, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_nome = QtWidgets.QLabel(self.page_3)
        self.label_nome.setGeometry(QtCore.QRect(130, 110, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        self.label_nome.setFont(font)
        self.label_nome.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome.setObjectName("label_nome")
        self.line_nome = QtWidgets.QLineEdit(self.page_3)
        self.line_nome.setGeometry(QtCore.QRect(210, 110, 261, 31))
        self.line_nome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.line_nome.setObjectName("line_nome")
        self.label_tel = QtWidgets.QLabel(self.page_3)
        self.label_tel.setGeometry(QtCore.QRect(130, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_tel.setFont(font)
        self.label_tel.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_tel.setObjectName("label_tel")
        self.line_tel = QtWidgets.QLineEdit(self.page_3)
        self.line_tel.setGeometry(QtCore.QRect(240, 170, 231, 31))
        self.line_tel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.line_tel.setInputMask("")
        self.line_tel.setText("")
        self.line_tel.setMaxLength(11)
        self.line_tel.setCursorPosition(0)
        self.line_tel.setObjectName("line_tel")
        self.label_apart = QtWidgets.QLabel(self.page_3)
        self.label_apart.setGeometry(QtCore.QRect(130, 250, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_apart.setFont(font)
        self.label_apart.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_apart.setObjectName("label_apart")
        self.line_apart = QtWidgets.QLineEdit(self.page_3)
        self.line_apart.setGeometry(QtCore.QRect(310, 240, 161, 31))
        self.line_apart.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.line_apart.setInputMask("")
        self.line_apart.setText("")
        self.line_apart.setMaxLength(4)
        self.line_apart.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_apart.setCursorPosition(0)
        self.line_apart.setDragEnabled(True)
        self.line_apart.setReadOnly(False)
        self.line_apart.setObjectName("line_apart")
        self.label_andar = QtWidgets.QLabel(self.page_3)
        self.label_andar.setGeometry(QtCore.QRect(130, 310, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_andar.setFont(font)
        self.label_andar.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_andar.setObjectName("label_andar")
        self.comboBox = QtWidgets.QComboBox(self.page_3)
        self.comboBox.setGeometry(QtCore.QRect(300, 310, 69, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.bt_salvar = QtWidgets.QPushButton(self.page_3)
        self.bt_salvar.setGeometry(QtCore.QRect(260, 400, 131, 41))
        self.bt_salvar.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_salvar.setFont(font)
        self.bt_salvar.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    \n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_salvar.setObjectName("bt_salvar")
        self.pages.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(110, 30, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.btt_salvar_1 = QtWidgets.QPushButton(self.page_4)
        self.btt_salvar_1.setGeometry(QtCore.QRect(270, 310, 161, 51))
        self.btt_salvar_1.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.btt_salvar_1.setObjectName("btt_salvar_1")
        self.line_4 = QtWidgets.QLineEdit(self.page_4)
        self.line_4.setGeometry(QtCore.QRect(460, 190, 113, 21))
        self.line_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_4.setMaxLength(1)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QLineEdit(self.page_4)
        self.line_3.setGeometry(QtCore.QRect(330, 190, 131, 21))
        self.line_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_3.setMaxLength(4)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QLineEdit(self.page_4)
        self.line_2.setGeometry(QtCore.QRect(220, 190, 113, 21))
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_2.setMaxLength(11)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QLineEdit(self.page_4)
        self.line.setGeometry(QtCore.QRect(110, 190, 113, 21))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setObjectName("line")
        self.label_nome_2 = QtWidgets.QLabel(self.page_4)
        self.label_nome_2.setGeometry(QtCore.QRect(140, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_nome_2.setFont(font)
        self.label_nome_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_2.setObjectName("label_nome_2")
        self.label_nome_3 = QtWidgets.QLabel(self.page_4)
        self.label_nome_3.setGeometry(QtCore.QRect(240, 160, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_nome_3.setFont(font)
        self.label_nome_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_3.setObjectName("label_nome_3")
        self.label_nome_4 = QtWidgets.QLabel(self.page_4)
        self.label_nome_4.setGeometry(QtCore.QRect(340, 160, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_nome_4.setFont(font)
        self.label_nome_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_4.setObjectName("label_nome_4")
        self.label_nome_5 = QtWidgets.QLabel(self.page_4)
        self.label_nome_5.setGeometry(QtCore.QRect(490, 160, 51, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_nome_5.setFont(font)
        self.label_nome_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_5.setObjectName("label_nome_5")
        self.pages.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.pages)
        self.bt_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cadastrar.setFont(font)
        self.bt_cadastrar.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_cadastrar.setObjectName("bt_cadastrar")
        self.verticalLayout.addWidget(self.bt_cadastrar)
        self.bt_cadastros = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cadastros.setFont(font)
        self.bt_cadastros.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_cadastros.setObjectName("bt_cadastros")
        self.verticalLayout.addWidget(self.bt_cadastros)
        self.bt_voltar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_voltar.setFont(font)
        self.bt_voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:2px;\n"
"    border-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition:0.5;\n"
"    opacity:0.7;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    border-style:outset;    \n"
"    border-width:3px;\n"
"    border-color:white;\n"
"}")
        self.bt_voltar.setObjectName("bt_voltar")
        self.verticalLayout.addWidget(self.bt_voltar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Gerenciamento"))
        self.bt_sair.setText(_translate("MainWindow", "SAIR"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">SISTEMA </span></p><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">DE</span></p><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">GERENCIAMENTO</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "FILTAR POR:"))
        self.bt_editar.setText(_translate("MainWindow", "EDITAR"))
        self.bt_deletar.setText(_translate("MainWindow", "DELETAR"))
        self.bt_pdf.setText(_translate("MainWindow", "PDF"))
        self.bt_excel.setText(_translate("MainWindow", "EXCEL"))
        self.label_4.setText(_translate("MainWindow", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TELEFONE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "APARTAMENTO"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ANDAR"))
        self.label_3.setText(_translate("MainWindow", "Cadastro De Moradores"))
        self.label_nome.setText(_translate("MainWindow", "Nome"))
        self.label_tel.setText(_translate("MainWindow", "Telefone"))
        self.label_apart.setText(_translate("MainWindow", "N/Apartamento"))
        self.label_andar.setText(_translate("MainWindow", "Andar:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.bt_salvar.setText(_translate("MainWindow", "Salvar"))
        self.label_5.setText(_translate("MainWindow", "             ALTERAÇÃO DE DADOS"))
        self.btt_salvar_1.setText(_translate("MainWindow", "SALVAR ALTERAÇÕES"))
        self.label_nome_2.setText(_translate("MainWindow", "NOME"))
        self.label_nome_3.setText(_translate("MainWindow", "TELEFONE"))
        self.label_nome_4.setText(_translate("MainWindow", "APARTEMENTO"))
        self.label_nome_5.setText(_translate("MainWindow", "ANDAR"))
        self.bt_cadastrar.setText(_translate("MainWindow", "CADASTRAR"))
        self.bt_cadastros.setText(_translate("MainWindow", "LISTA DE CADASTROS"))
        self.bt_voltar.setText(_translate("MainWindow", "VOLTAR"))
