
CREATE TABLE `cadastro_moradores`.`cadastro` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR (11) NOT NULL,
  `APARTAMENTO` VARCHAR(10) NOT NULL,
  `ANDAR` VARCHAR(10),
  PRIMARY KEY (`ID`));

